import './globals.css'
import {  Fjalla_One} from 'next/font/google'

const fjala = Fjalla_One({ weight: "400",subsets:["latin"] })

export const metadata = {
  title: 'Moncef potfolio',
  description: 'Generated by Moncef',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`   items-center flex-col flex    gap-6 bg-main text-main600 w-full min-h-screen ${fjala.className}`}>
        {children}
        </body>
    </html>
  )
}
