import './globals.css'
import {  Fjalla_One} from 'next/font/google'

const fjala = Fjalla_One({ weight: "400",subsets:["latin"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`  bg-main text-main600 w-full min-h-screen ${fjala.className}`}>{children}</body>
    </html>
  )
}
